### ISSUE TITLE
TLS secret is not getting created.

### ISSUE THREAD

**Issue by nirmalpathak** [gyselroth/kube-ldap#28]
I'm facing an issue while creating TLS secret. I get following output while deploying the kube-ldap.

```
$ kubectl create -f kube-ldap.yaml 
secret/kube-ldap-jwt-key created
secret/kube-ldap-ldap-bind-credentials created
deployment.apps/kube-ldap created
service/kube-ldap created
The Secret "kube-ldap-tls" is invalid: 
* data[tls.crt]: Required value
* data[tls.key]: Required value
```

Here is snippet TLS secret section of my kube-ldap.yaml file,

```
---
apiVersion: v1
data:
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tIE1JSURFVENDQWZtZ0F3SUJBZ0lKQUtiemcwS3BlQkZiTUEwR0NTcUdTSWIzRFFFQkN3VUFNQjh4SFRBYkJnTlYgQkFNTUZHczRjeTVqWkdVdWMzbHRZVzUwWldNdVkyOXRNQjRYRFRFNU1EWXlPREEwTXpRMU1Gb1hEVEk1TURZeSBOVEEwTXpRMU1Gb3dIekVkTUJzR0ExVUVBd3dVYXpoekxtTmtaUzV6ZVcxaGJuUmxZeTVqYjIwd2d--truncated base64 encode cert--WVlaNExGTU5oSjhkIGkxRko1eGxQUHZ1L1BBR2hzQklqc1dpWWxNSmJzN1R5VFhuNzdqSmszd3M5bHZ3MDJuS25NNlE4L2ZEUHBPZUEgVDdOT1pOU0dxMVg0WEVjQnZXamFIWnVKRkVFMyAtLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLSBNSUlFcFFJQkFBS0NBUUVBdWN3Tk01U--truncated base64 encode key--UHVTMlp3T2p3UitoeGpjaGFKSHNRbGl1UG1jY2JZdDZudC9PL3BqTHNOVFc2TGQgV3BTQ0tMcXNxcFVLVC8zSGQ4VVdxb2tqR28vNmJNdVExcnJ1bFc4bFlEbUExQzVrODdUWTZ2VVJjVWhNN2ExYyBxTzFuQ3M5ZmxSeUhId1pVNmoxMmNBSmV1OWRBSFR6RWRhMUNlOWJoQ1BmbnAwMkVrUFNRM3FBPSAtLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
kind: Secret
metadata:
  name: kube-ldap-tls
  namespace: kube-system
type: kubernetes.io/tls
---
```

Am I missing something?
